### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [AndreiDiving/first-web-project#1]
1)
требования к высоте не выполнены
![image](https://user-images.githubusercontent.com/8464662/91178084-51121a80-e6ed-11ea-9b82-f59e29f8f08c.png)

2)
цвет элементов не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/91178147-66874480-e6ed-11ea-97d5-154f8f54dffd.png)

3)
шрифт не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/91178263-92a2c580-e6ed-11ea-8699-1343d4cc98ca.png)

4)
размер шрифта не соответствует макету для всех точек
![image](https://user-images.githubusercontent.com/8464662/91178458-d269ad00-e6ed-11ea-878a-b9d9f8975ffc.png)

**Comment by Alecto** [comment]
1 - не исправлено 

2 - не исправлено

4 - не исправлено
должно быть ровно 18, откуда дроби? на меньших разрешениях все становится нормально
![image](https://user-images.githubusercontent.com/8464662/91311541-dfed6880-e7bb-11ea-8bd3-877d0dcbaf4b.png)

**Comment by AndreiDiving** [comment]
Repository
https://github.com/AndreiDiving/first-web-project
page
https://andreidiving.github.io/first-web-project/

Надеюсь  получилось исрпавить


ср, 26 авг. 2020 г. в 21:49, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
да, теперь все исправлено.
работа принята.

чт, 27 серп. 2020 о 14:22 AndreiDiving <notifications@github.com> пише:

**Comment by Alecto** [comment]
напишите ФИО и группу, в письме с гитхаб инфа потерялась.

чт, 27 серп. 2020 о 15:30 Андрей Фоменко <fomenkoandrey1978@gmail.com> пише:

**Comment by AndreiDiving** [comment]
SkillUp FrontEnd, Крамаренко Андрей вт/чт 17:00

чт, 27 авг. 2020 г. в 20:31, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
отметил.
напомните, у вас полностью сдана работа №5?
в журнале отмечена частичная сдача.

чт, 27 серп. 2020 о 19:23 AndreiDiving <notifications@github.com> пише:
